hello_world initial
CoveoWhisper/NLPAPI pull request #1
Opened 2018-03-26 17:22 UTC by daesolus

2018-03-30 14:18 UTC, WebF0x commented on README.md
> +#NL API
NLP*

2018-03-30 14:51 UTC, WebF0x requested changes

2018-03-30 14:51 UTC, WebF0x commented on README.md
> +#NL API
NLP*

2018-03-30 14:51 UTC, WebF0x commented on api/NLJSONEncoder.py
> +class NLJSONEncoder(JSONEncoder):
NLP*?

2018-03-30 14:51 UTC, WebF0x commented on api/NLJSONEncoder.py
> +                'confidence': obj.confidence,
Selon le accuracy test, il semble que ce sont les Intent qui ont un niveau de confidence et non les Entity

![image](https://user-images.githubusercontent.com/5454643/38141229-255a0094-3405-11e8-8d7e-7d1509752acf.png)

2018-03-30 14:51 UTC, WebF0x commented on requirements.txt
> +tox==2.9.1
Je pense pas que tox soit nécessaire, est-ce que ça marche sans?
D'après moi le user est deja obligé d'avoir tox pour utiliser ce fichier donc on aurait pas de besoin

2018-03-30 14:51 UTC, WebF0x commented on setup.py
> +    name='Natural Language API',
Natural Language Processing* API

2018-03-30 14:51 UTC, WebF0x commented on test/test_entity.py
> +        intent_name = "Une intention"
Pas très grave mais je préfèrais rester en anglais partout puisque ça va être open source

2018-03-30 14:51 UTC, WebF0x commented on test/test_entity.py
> +        self.assertEqual(intent_name, intent.name)
Une bonne pratique est d'utiliser un nouvel objet quand on compare dans un test pour éviter par exemple que le test passe même si l'intent_name est modifé. Ex qui devrait briser mais qui passe:

![image](https://user-images.githubusercontent.com/5454643/38141675-424296c4-3407-11e8-9234-2475af565c5a.png)

Tu peux hard coder 2 fois le string dans le test et enlever la variable intent_name.
Obviously ça marche dans notre cas plutôt simple, mais c'est une bonne habitude à prendre

2018-03-30 14:52 UTC, WebF0x commented
Les tests ne roulent pas, il manque "nose" dans les requirements et cette ligne dans le tox.ini et je pense que ça va marcher:

https://github.com/CoveoWhisper/dialogflow_accuracy_test/blob/master/tox.ini#L10

2018-03-30 14:54 UTC, WebF0x commented
Il faut "gitignorer" le fichier Manifest

![image](https://user-images.githubusercontent.com/5454643/38141997-ad55672e-3408-11e8-8d7e-adcbdd6dc792.png)

2018-03-31 18:34 UTC, daesolus commented on requirements.txt
> +tox==2.9.1
non on a seulement besoin de PIP. Ca va installer tox à notre place.

2018-03-31 19:41 UTC, merged