Add Config file and test. Add nose as dependancy
CoveoWhisper/NLPAPI pull request #4
Opened 2018-03-31 23:59 UTC by daesolus

2018-04-01 00:00 UTC, daesolus commented on api/config.ini
> +API_KEY = 404
Je vais faire un fichier de config de test pour mon autre tâche pour pas qu'on soit dépendant de ca.

2018-04-02 16:35 UTC, WebF0x requested changes

2018-04-02 16:35 UTC, WebF0x commented on api/config.py
> +        script_dir = os.path.dirname(__file__)
je préfèrerais d'éviter les abbréviations dans les noms de variables parce que ça devient plus dur à comprendre au fil que le code grossit (directory et absolute)

2018-04-02 16:35 UTC, WebF0x commented on api/config.py
> +        found = parser.read(abs_file_path)
parser.read() retourne une liste de fichiers lus et non un boolean, peut-être renommer cette variable?
https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read

2018-04-03 15:09 UTC, merged